/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RcaRouteImport } from './routes/rca'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCaptionRouteImport } from './routes/api/caption'

const RcaRoute = RcaRouteImport.update({
  id: '/rca',
  path: '/rca',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCaptionRoute = ApiCaptionRouteImport.update({
  id: '/api/caption',
  path: '/api/caption',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/copilot': typeof CopilotRoute
  '/graph': typeof GraphRoute
  '/rca': typeof RcaRoute
  '/api/caption': typeof ApiCaptionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/copilot': typeof CopilotRoute
  '/graph': typeof GraphRoute
  '/rca': typeof RcaRoute
  '/api/caption': typeof ApiCaptionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/copilot': typeof CopilotRoute
  '/graph': typeof GraphRoute
  '/rca': typeof RcaRoute
  '/api/caption': typeof ApiCaptionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/copilot'
    | '/graph'
    | '/rca'
    | '/api/caption'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analytics' | '/copilot' | '/graph' | '/rca' | '/api/caption'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/copilot'
    | '/graph'
    | '/rca'
    | '/api/caption'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CopilotRoute: typeof CopilotRoute
  GraphRoute: typeof GraphRoute
  RcaRoute: typeof RcaRoute
  ApiCaptionRoute: typeof ApiCaptionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rca': {
      id: '/rca'
      path: '/rca'
      fullPath: '/rca'
      preLoaderRoute: typeof RcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/caption': {
      id: '/api/caption'
      path: '/api/caption'
      fullPath: '/api/caption'
      preLoaderRoute: typeof ApiCaptionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CopilotRoute: CopilotRoute,
  GraphRoute: GraphRoute,
  RcaRoute: RcaRoute,
  ApiCaptionRoute: ApiCaptionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
